/* Copyright (c) 2021-2024 MIT 6.102/6.031 course staff, all rights reserved.
 * Redistribution of original or derived work requires permission of course staff.
 */

/** String-based commands provided by the meme generation system. @module */

import { type MemeExpression, parse } from './expression.ts';
import { type Canvas, createCanvas, type ImageLibrary } from './imagelibrary.ts';

/*
 * PS3 instructions: these are required functions.
 * You MUST NOT change the names, type signatures, or specs of these functions.
 */

/**
 * Compute the size of an image meme expression.
 *
 * @param expression the expression to use
 * @param library the library of named image files
 * @returns "WxH" (in the same syntax as the corresponding part of the @ resize operator)
 *          representing the width W and height H of the image generated by the expression, 
 *          according to the language definition in the PS3 handout
 * @throws Error if the size cannot be computed
 */
export function size(expression: MemeExpression, library: ImageLibrary): string {
    const expSize = expression.size(library);
    return `${expSize.width}x${expSize.height}`;
}

/**
 * Generate the image meme of an expression.
 *
 * @param expression the expression to generate
 * @param library the library of named image files
 * @returns a `data:` URL for the image generated by the expression, according to the language
 *          definition in the PS3 handout. See {@linkcode Canvas.toDataURL}.
 * @throws Error if the image cannot be generated
 */
export function image(expression: MemeExpression, library: ImageLibrary): string {
    return expression.image(library).toDataURL();
}